name: 'cms'
version: '1.0.0'
config-version: 2
profile: 'cms'

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  cms:
    staging:
      +schema: stg
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
