/*
  One-time account setup for the Medicare Cost & Quality project.
  Idempotent. Run from a role with ACCOUNTADMIN.

      snow sql -f snowflake/setup/01_account_objects.sql
*/

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS LOAD_WH
    WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'Ingest CMS extracts into RAW';

CREATE WAREHOUSE IF NOT EXISTS XFORM_WH
    WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE COMMENT = 'dbt transformations';

CREATE WAREHOUSE IF NOT EXISTS ANALYST_WH
    WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE STATEMENT_TIMEOUT_IN_SECONDS = 60
    COMMENT = 'Ad-hoc analyst queries';

CREATE DATABASE IF NOT EXISTS CMS
    COMMENT = 'Medicare inpatient cost & quality — analytics warehouse';

USE DATABASE CMS;

CREATE SCHEMA IF NOT EXISTS RAW   COMMENT = 'Untouched landing tables — exact CSV shape';
CREATE SCHEMA IF NOT EXISTS STG   COMMENT = 'Renamed/cast/cleaned';
CREATE SCHEMA IF NOT EXISTS MARTS COMMENT = 'Star schema — two facts, conformed dims';

CREATE STAGE IF NOT EXISTS RAW.CMS_STAGE
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 NULL_IF = ('', 'NA', 'Not Available'))
    COMMENT = 'Landing stage for the CMS CSV extracts';

CREATE ROLE IF NOT EXISTS WAREHOUSE_DEV COMMENT = 'Developer role';

GRANT USAGE ON DATABASE CMS TO ROLE WAREHOUSE_DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CMS TO ROLE WAREHOUSE_DEV;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CMS.RAW   TO ROLE WAREHOUSE_DEV;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CMS.STG   TO ROLE WAREHOUSE_DEV;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CMS.MARTS TO ROLE WAREHOUSE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE CMS TO ROLE WAREHOUSE_DEV;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN DATABASE CMS TO ROLE WAREHOUSE_DEV;
GRANT USAGE ON WAREHOUSE LOAD_WH    TO ROLE WAREHOUSE_DEV;
GRANT USAGE ON WAREHOUSE XFORM_WH   TO ROLE WAREHOUSE_DEV;
GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE WAREHOUSE_DEV;

-- GRANT ROLE can't take IDENTIFIER(CURRENT_USER()); use a session var.
SET grantee = CURRENT_USER();
GRANT ROLE WAREHOUSE_DEV TO USER IDENTIFIER($grantee);

SELECT 'setup complete' AS status, CURRENT_ACCOUNT() AS account, CURRENT_DATABASE() AS db;
SHOW SCHEMAS IN DATABASE CMS;
